apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
       - name: backend
         image: hanibhavsar/e-commerce-backend:02523c37a2129a025ba6309d1af11c27243cf6e0
         ports:
              - containerPort: 8080

