apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hanibhavsar/e-commerce-frontend:02523c37a2129a025ba6309d1af11c27243cf6e0
        ports:
         - containerPort: 3000

