name: E-com-project CI/CD
on:
  push:
    branches:
      - main

job:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name : docker build and push for frontend
        run : |
          docker-build -t ${{ secrets.DOCKER_USERNAME }}/e-commerce-frontend: ${{GITHUB_SHA}} ./E-Commerce_Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerce-frontend: ${{GITHUB_SHA}}
          
      - name : docker build and push for backend
        run : |
          docker-build -t ${{ secrets.DOCKER_USERNAME }}/e-commerce-backend: ${{GITHUB_SHA}} ./E-Commerce_Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/e-commerce-backend: ${{GITHUB_SHA}}
  
